### ISSUE TITLE
OpenProject 8.0.1

### ISSUE THREAD

**Issue by isralfaro** [zaproo/pm2gitlab#1]
I can not make this work with OpenProject 8.0.1 – I haven't seen any documented case on which this plugin successfully works and also haven't seen detailed installation/configuration instructions.

Will this work on OpenProject 8.0.1?

**Comment by zaproo-support** [comment]
Latest supported version is 7.4.4

At the moment we are not planning to make it work with later versions.

**Comment by brennebeck** [comment]
>At the moment we are not planning to make it work with later versions.

Hi @indrekpihor  - is there a particular reason there are no plans to support newer versions?

**Comment by zaproo-support** [comment]
yes, sure. We are switching to www.embilo.com.

**Comment by brennebeck** [comment]
Ah, thanks for the reference. It doesn't seem to be open source or
self-hosted though, right? Or did I just miss that?
ᐧ

**Comment by zaproo-support** [comment]
You are right.

**Comment by brennebeck** [comment]
@indrekpihor any chance you would be able to point me in the right direction for how to fix? I haven't worked on OpenProject before or dug into the docs yet. I understand this might be asking a lot, as I'm sure you're busy, but as you don't plan to support the new release it would be helpful if I had a starting point on how to migrate. Either way, thanks.

**Comment by Tofandel** [comment]
I'd be happy to help make it work on v8 of open project on a fork but no idea where to start as well and no time yet

**Comment by maxxer** [comment]
There's an [ongoing effort](https://gitlab.com/mengxin/gitlab-ce/merge_requests/1/diffs) to develop OP integration into GitLab. 

Keep a look there, in order to avoid work duplication

**Comment by zaproo-support** [comment]
Would be nice if there would be native integration with Gitlab, as in our practice our module did not come into every-day use in our team. The Integration anyway will post only one specific sentence to Open project. So the @maxxer link to GL development is much better. Better wait for it. @Tofandel @brennebeck

**Comment by Tofandel** [comment]
Mmm this only links the issue tracker trivially with a task (post a comment to open project when issue is resolved) .. I was thinking a plugin from openproject to be able to create new issues to gitlab when a task is created and comments published there as well, maybe even the ability to create branches for a task and when branch merged to close the task like the github integration
